services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_clone
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - whatsapp_clone
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp_clone
    command: ["start-dev"]

networks:
  whatsapp_clone:
    driver: bridge

volumes:
  postgres:
    driver: local